"""create booking flow tables

Revision ID: 20260312_0004
Revises: 20260307_0003
Create Date: 2026-03-12 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260312_0004"
down_revision: Union[str, None] = "20260307_0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS booking_question_templates (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            professional_id UUID NOT NULL REFERENCES professionals(user_id) ON DELETE CASCADE,
            prompt TEXT NOT NULL,
            display_order SMALLINT NOT NULL DEFAULT 1,
            is_required BOOLEAN NOT NULL DEFAULT TRUE,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_booking_question_templates_order UNIQUE (professional_id, display_order)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS booking_question_responses (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            professional_id UUID NOT NULL REFERENCES professionals(user_id) ON DELETE CASCADE,
            client_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            template_question_id BIGINT NOT NULL REFERENCES booking_question_templates(id) ON DELETE CASCADE,
            answer TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_booking_question_responses_per_user UNIQUE (professional_id, client_user_id, template_question_id)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS bookings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            booking_reference VARCHAR(64) NOT NULL UNIQUE,
            professional_id UUID NOT NULL REFERENCES professionals(user_id) ON DELETE CASCADE,
            client_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
            service_name VARCHAR(255) NOT NULL,
            status VARCHAR(32) NOT NULL DEFAULT 'pending',
            scheduled_for TIMESTAMPTZ,
            is_immediate BOOLEAN NOT NULL DEFAULT FALSE,
            notes TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS booking_payments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
            provider VARCHAR(32) NOT NULL,
            provider_order_id VARCHAR(128) NOT NULL UNIQUE,
            amount NUMERIC(10,2) NOT NULL,
            currency VARCHAR(8) NOT NULL DEFAULT 'INR',
            status VARCHAR(32) NOT NULL DEFAULT 'created',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_booking_question_templates_professional ON booking_question_templates (professional_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_booking_question_responses_user_professional ON booking_question_responses (client_user_id, professional_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_bookings_professional_client ON bookings (professional_id, client_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_booking_payments_booking ON booking_payments (booking_id)"
    )

    # Seed two default mandatory questions for each professional if not configured.
    op.execute(
        """
        INSERT INTO booking_question_templates (professional_id, prompt, display_order, is_required, is_active)
        SELECT p.user_id,
            'What outcome do you expect in the next 4-6 weeks?',
            1,
            TRUE,
            TRUE
        FROM professionals p
        ON CONFLICT (professional_id, display_order) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO booking_question_templates (professional_id, prompt, display_order, is_required, is_active)
        SELECT p.user_id,
            'Any routine, food, or schedule constraints we should consider?',
            2,
            TRUE,
            TRUE
        FROM professionals p
        ON CONFLICT (professional_id, display_order) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS booking_payments")
    op.execute("DROP TABLE IF EXISTS bookings")
    op.execute("DROP TABLE IF EXISTS booking_question_responses")
    op.execute("DROP TABLE IF EXISTS booking_question_templates")
