"""v1_1_baseline_schema

Revision ID: f577acd2eef7
Revises: 
Create Date: 2026-03-21 18:09:27.431502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "f577acd2eef7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table('holistic_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('query_tag', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pricing_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pricing_currency', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('sessions_included_total', sa.Integer(), nullable=False),
    sa.Column('package_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.String(length=32), nullable=True),
    sa.Column('user_subtype', sa.String(length=32), nullable=True),
    sa.Column('user_status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('wolistic_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('read_time', sa.String(length=50), server_default='5 min read', nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wolistic_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('website_name', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wolistic_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('website_name', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professionals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('membership_tier', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Integer(), server_default='0', nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('sex', sa.String(), server_default='undisclosed', nullable=False),
    sa.Column('short_bio', sa.String(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_online', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rating_avg', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('profile_completeness', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('booking_question_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professional_id', 'display_order', name='uq_booking_question_templates_order')
    )
    op.create_table('bookings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_reference', sa.String(length=64), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('client_user_id', sa.UUID(), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_immediate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_table('holistic_team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('sessions_included', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['holistic_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'professional_id', name='uq_holistic_team_member_unique')
    )
    op.create_table('professional_approaches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_boost_impressions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('surface', sa.String(length=32), nullable=False),
    sa.Column('slot_position', sa.SmallInteger(), nullable=False),
    sa.Column('placement_label', sa.String(length=32), server_default='Boosted', nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('user_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('user_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('radius_km', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_certifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('issued_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_education',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('education', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_expertise_areas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_featured_index',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('sort_rank', sa.Integer(), nullable=False),
    sa.Column('rank_score', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('membership_tier', sa.String(length=32), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professional_id')
    )
    op.create_table('professional_gallery',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_languages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_service_areas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('radius_km', sa.Integer(), server_default='300', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_services',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_brief', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('offers', sa.String(), nullable=True),
    sa.Column('negotiable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('offer_type', sa.String(length=20), server_default='none', nullable=False),
    sa.Column('offer_value', sa.Integer(), nullable=True),
    sa.Column('offer_label', sa.String(length=100), nullable=True),
    sa.Column('offer_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offer_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('duration_value', sa.Integer(), nullable=False),
    sa.Column('duration_unit', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_session_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_subcategories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favourites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'professional_id')
    )
    op.create_table('booking_payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_order_id', sa.String(length=128), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('provider_signature', sa.String(length=512), nullable=True),
    sa.Column('provider_payload', sa.JSON(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='INR', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='created', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_order_id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_table('booking_question_responses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('client_user_id', sa.UUID(), nullable=False),
    sa.Column('template_question_id', sa.BigInteger(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.ForeignKeyConstraint(['template_question_id'], ['booking_question_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professional_id', 'client_user_id', 'template_question_id', name='uq_booking_question_responses_per_user')
    )

    op.create_index('ix_users_status_id', 'users', ['user_status', 'id'], unique=False)

    op.create_index('ix_professionals_profile_completeness', 'professionals', ['profile_completeness'], unique=False)
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_professionals_lat_lng_not_null
        ON professionals (latitude, longitude)
        WHERE latitude IS NOT NULL AND longitude IS NOT NULL
        """
    )

    op.create_index('ix_holistic_teams_scope', 'holistic_teams', ['scope'], unique=False)
    op.create_index('ix_holistic_teams_query_tag', 'holistic_teams', ['query_tag'], unique=False)
    op.create_index('ix_holistic_teams_source_type', 'holistic_teams', ['source_type'], unique=False)
    op.create_index('ix_holistic_teams_active_created', 'holistic_teams', ['is_active', 'created_at'], unique=False)
    op.create_index('ix_holistic_team_members_team_id', 'holistic_team_members', ['team_id'], unique=False)
    op.create_index('ix_holistic_team_members_professional_id', 'holistic_team_members', ['professional_id'], unique=False)

    op.create_index('ix_professional_featured_index_sort_rank', 'professional_featured_index', ['sort_rank'], unique=False)
    op.create_index('ix_professional_featured_index_updated_at', 'professional_featured_index', ['updated_at'], unique=False)

    op.create_index('ix_professional_services_professional_id', 'professional_services', ['professional_id'], unique=False)
    op.create_index('ix_professional_services_professional_active_mode', 'professional_services', ['professional_id', 'is_active', 'mode'], unique=False)
    op.create_index('ix_professional_reviews_professional_id', 'professional_reviews', ['professional_id'], unique=False)
    op.create_index('ix_professional_service_areas_professional_id', 'professional_service_areas', ['professional_id'], unique=False)
    op.create_index('ix_professional_languages_professional_id', 'professional_languages', ['professional_id'], unique=False)
    op.create_index('ix_professional_subcategories_professional_id', 'professional_subcategories', ['professional_id'], unique=False)
    op.create_index('ix_professional_session_types_professional_id', 'professional_session_types', ['professional_id'], unique=False)
    op.create_index('ix_professional_approaches_professional_id', 'professional_approaches', ['professional_id'], unique=False)
    op.create_index('ix_professional_availability_professional_id', 'professional_availability', ['professional_id'], unique=False)
    op.create_index('ix_professional_gallery_professional_id', 'professional_gallery', ['professional_id'], unique=False)
    op.create_index('ix_professional_expertise_areas_professional_id', 'professional_expertise_areas', ['professional_id'], unique=False)
    op.create_index('ix_professional_certifications_professional_id', 'professional_certifications', ['professional_id'], unique=False)
    op.create_index('ix_professional_boost_impressions_professional_id', 'professional_boost_impressions', ['professional_id'], unique=False)
    op.create_index('ix_professional_boost_impressions_surface_created_at', 'professional_boost_impressions', ['surface', 'created_at'], unique=False)

    op.create_index('ix_booking_payments_booking', 'booking_payments', ['booking_id'], unique=False)
    op.create_index('ix_booking_question_templates_professional', 'booking_question_templates', ['professional_id'], unique=False)
    op.create_index('ix_booking_question_responses_user_professional', 'booking_question_responses', ['client_user_id', 'professional_id'], unique=False)
    op.create_index('ix_bookings_professional_client', 'bookings', ['professional_id', 'client_user_id'], unique=False)

    op.create_index('ix_user_favourites_user_id', 'user_favourites', ['user_id'], unique=False)
    op.create_index('ix_user_favourites_professional_id', 'user_favourites', ['professional_id'], unique=False)

    op.execute(
        """
        CREATE OR REPLACE FUNCTION public.bootstrap_professional_from_user()
        RETURNS TRIGGER AS $$
        DECLARE
            base_username TEXT;
            generated_username TEXT;
        BEGIN
            base_username := lower(regexp_replace(split_part(COALESCE(NEW.email, ''), '@', 1), '[^a-z0-9]+', '-', 'g'));
            base_username := trim(both '-' from base_username);

            IF base_username IS NULL OR base_username = '' THEN
                base_username := 'user';
            END IF;

            generated_username := left(base_username || '-' || left(replace(NEW.id::text, '-', ''), 8), 100);

            INSERT INTO public.professionals (
                user_id,
                username,
                specialization,
                experience_years,
                sex
            )
            VALUES (
                NEW.id,
                generated_username,
                'Wellness Expert',
                0,
                'undisclosed'
            )
            ON CONFLICT (user_id) DO NOTHING;

            INSERT INTO public.professional_services (
                professional_id,
                name,
                short_brief,
                price,
                offers,
                negotiable,
                offer_type,
                offer_value,
                offer_label,
                mode,
                duration_value,
                duration_unit,
                is_active
            )
            SELECT
                NEW.id,
                'Initial Consultation',
                'Intro consultation to understand your goals and next steps.',
                250,
                '100% refund as credits',
                FALSE,
                'cashback',
                250,
                '100% refund as credits',
                'online',
                15,
                'mins',
                TRUE
            WHERE NOT EXISTS (
                SELECT 1
                FROM public.professional_services s
                WHERE s.professional_id = NEW.id
            );

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;
        """
    )
    op.execute("DROP TRIGGER IF EXISTS trg_bootstrap_professional_from_user ON public.users;")
    op.execute(
        """
        CREATE TRIGGER trg_bootstrap_professional_from_user
        AFTER INSERT ON public.users
        FOR EACH ROW
        WHEN (NEW.user_type = 'partner')
        EXECUTE FUNCTION public.bootstrap_professional_from_user();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_bootstrap_professional_from_user ON public.users;")
    op.execute("DROP FUNCTION IF EXISTS public.bootstrap_professional_from_user();")

    op.drop_index('ix_user_favourites_professional_id', table_name='user_favourites')
    op.drop_index('ix_user_favourites_user_id', table_name='user_favourites')
    op.drop_index('ix_bookings_professional_client', table_name='bookings')
    op.drop_index('ix_booking_question_responses_user_professional', table_name='booking_question_responses')
    op.drop_index('ix_booking_question_templates_professional', table_name='booking_question_templates')
    op.drop_index('ix_booking_payments_booking', table_name='booking_payments')

    op.drop_index('ix_professional_boost_impressions_surface_created_at', table_name='professional_boost_impressions')
    op.drop_index('ix_professional_boost_impressions_professional_id', table_name='professional_boost_impressions')
    op.drop_index('ix_professional_certifications_professional_id', table_name='professional_certifications')
    op.drop_index('ix_professional_expertise_areas_professional_id', table_name='professional_expertise_areas')
    op.drop_index('ix_professional_gallery_professional_id', table_name='professional_gallery')
    op.drop_index('ix_professional_availability_professional_id', table_name='professional_availability')
    op.drop_index('ix_professional_approaches_professional_id', table_name='professional_approaches')
    op.drop_index('ix_professional_session_types_professional_id', table_name='professional_session_types')
    op.drop_index('ix_professional_subcategories_professional_id', table_name='professional_subcategories')
    op.drop_index('ix_professional_languages_professional_id', table_name='professional_languages')
    op.drop_index('ix_professional_service_areas_professional_id', table_name='professional_service_areas')
    op.drop_index('ix_professional_reviews_professional_id', table_name='professional_reviews')
    op.drop_index('ix_professional_services_professional_active_mode', table_name='professional_services')
    op.drop_index('ix_professional_services_professional_id', table_name='professional_services')

    op.drop_index('ix_professional_featured_index_updated_at', table_name='professional_featured_index')
    op.drop_index('ix_professional_featured_index_sort_rank', table_name='professional_featured_index')

    op.drop_index('ix_holistic_team_members_professional_id', table_name='holistic_team_members')
    op.drop_index('ix_holistic_team_members_team_id', table_name='holistic_team_members')
    op.drop_index('ix_holistic_teams_active_created', table_name='holistic_teams')
    op.drop_index('ix_holistic_teams_source_type', table_name='holistic_teams')
    op.drop_index('ix_holistic_teams_query_tag', table_name='holistic_teams')
    op.drop_index('ix_holistic_teams_scope', table_name='holistic_teams')

    op.execute("DROP INDEX IF EXISTS ix_professionals_lat_lng_not_null")
    op.drop_index('ix_professionals_profile_completeness', table_name='professionals')
    op.drop_index('ix_users_status_id', table_name='users')

    op.drop_table('booking_question_responses')
    op.drop_table('booking_payments')
    op.drop_table('user_favourites')
    op.drop_table('professional_subcategories')
    op.drop_table('professional_session_types')
    op.drop_table('professional_services')
    op.drop_table('professional_service_areas')
    op.drop_table('professional_reviews')
    op.drop_table('professional_languages')
    op.drop_table('professional_gallery')
    op.drop_table('professional_featured_index')
    op.drop_table('professional_expertise_areas')
    op.drop_table('professional_education')
    op.drop_table('professional_certifications')
    op.drop_table('professional_boost_impressions')
    op.drop_table('professional_availability')
    op.drop_table('professional_approaches')
    op.drop_table('holistic_team_members')
    op.drop_table('bookings')
    op.drop_table('booking_question_templates')
    op.drop_table('professionals')
    op.drop_table('wolistic_services')
    op.drop_table('wolistic_products')
    op.drop_table('wolistic_articles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('holistic_teams')
    # ### end Alembic commands ###
